eureka:
  client:
#    register-with-eureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8084
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: love #路由的ID
          uri: lb://consumer-weather #匹配后路由地址
          predicates: # 断言，路径相匹配的进行路由
            - Path=/customer-module/**
          filters:
            - StripPrefix=1 # customer-module去掉之后 下发至微服务

  application:
    name: gateway
  main:
    web-application-type: reactive